<?php

use App\FraudControl\Constants\DAFActions;
use App\ThreeDS\Services\Helpers\OutOfBandServiceTracer;
use App\ThreeDS\Services\Helpers\QuestionnaireServiceTracer;
use PlacetoPay\ThreeDsSecureBase\Constants\Common\MessageType;
use PlacetoPay\ThreeDsSecureBase\Constants\Versions\V220\TransactionStatus;

return [
    'titles' => [
        'index' => 'Authentications',
        'decoupled_authentications' => 'Decoupled authentications',
        'unselected_decoupled_authentications' => 'Unselected authentications',
        'workspace_decoupled_authentications' => 'My authentications',
        'processing_decoupled_authentications' => 'Authentications by other users',
        'messages' => 'Authentication messages',
        'traces' => 'Authentication traces',
        'export' => 'Authentication report',
        'indicators' => 'Authentication indicators',
        'data' => 'Message Data',
    ],
    'invalid_range' => 'The difference in days for the date range must not exceed :number days',
    'statuses' => [
        TransactionStatus::SUCCESSFUL => [
            'label' => '[Y] Authenticated',
            'description' => ' Authentication Verification Successful',
        ],
        TransactionStatus::NOT_AUTHENTICATED => [
            'label' => '[N] Not authenticated',
            'description' => 'Not Authenticated/Account Not Verified; Transaction denied',
        ],
        TransactionStatus::COULD_NOT_BE_PERFORMED => [
            'label' => '[U] Not Performed',
            'description' => 'Authentication/Account Verification Could Not Be Performed; Technical or other problem, as indicated in the ARes or RReq',
        ],
        TransactionStatus::ATTEMPTS_PROCESSING_PERFORMED => [
            'label' => '[A] Attempt',
            'description' => 'Attempts Processing Performed; Not Authenticated/Verified, but a proof of attempted authentication/verification is provided ',
        ],
        TransactionStatus::CHALLENGE_REQUIRED => [
            'label' => '[C] Challenge',
            'description' => 'Challenge Required; Additional authentication is required using the CReq/CRes',
        ],
        TransactionStatus::CHALLENGE_REQUIRED_DECOUPLE => [
            'label' => '[D] Decoupled',
            'description' => 'Challenge Required; Decoupled Authentication confirmed',
        ],
        TransactionStatus::REJECTED => [
            'label' => '[R] Rejected',
            'description' => 'Authentication/ Account Verification Rejected; Issuer is rejecting authentication/verification and request that authorisation not be attempted.',
        ],
        TransactionStatus::INFORMATION_ONLY => [
            'label' => '[I] Informational',
            'description' => ' Informational Only; 3DS Requestor challenge preference acknowledged',
        ],
    ],
    'acct_info' => [
        'ch_acc_age_ind' => [
            '01' => 'No account (guest check-out)',
            '02' => 'Created during this transaction',
            '03' => 'Less than 30 days',
            '04' => '30−60 days',
            '05' => 'More than 60 days',
        ],
        'ch_acc_change_ind' => [
            '01' => 'Changed during this transaction',
            '02' => 'Less than 30 days',
            '03' => '30−60 days',
            '04' => 'More than 60 days',
        ],
        'ch_acc_pw_change_ind' => [
            '01' => 'No change',
            '02' => 'Changed during this transaction',
            '03' => 'Less than 30 days',
            '04' => '30−60 days',
            '05' => 'More than 60 days',
        ],
        'payment_acc_ind' => [
            '01' => 'No account (guest check-out)',
            '02' => 'During this transaction',
            '03' => 'Less than 30 days',
            '04' => '30−60 days',
            '05' => 'More than 60 days',
        ],
        'ship_address_usage_ind' => [
            '01' => 'This transaction',
            '02' => 'Less than 30 days',
            '03' => '30−60 days',
            '04' => 'More than 60 days',
        ],
        'ship_name_indicator' => [
            '01' => 'Account Name identical to shipping Name',
            '02' => 'Account Name different than shipping Name',
        ],
        'suspicious_acc_activity' => [
            '01' => 'No suspicious activity has been observed',
            '02' => 'Suspicious activity has been observed',
        ],
    ],
    'no_authentication_found' => 'No authentications found',
    'component' => [
        'error' => 'Error generated by: <strong>:causer</strong>',
        'C' => '3DS SDK',
        'S' => '3DS Server',
        'D' => 'Directory server',
        'A' => 'ACS',
    ],
    'messages' => [
        'resolve' => 'The authentication was successfully resolved.',
        'not_resolve' => 'The authentication is not decoupled.',
        'in_process' => 'The authentication is being resolved by another user.',
        'expiration' => 'You have exceeded the maximum time to resolve this authentication.',
        'no_information_provided' => 'No Cardholder Account Information was provided',
        'free_transaction' => 'The transaction was successfully released.',
        'type' => 'Message type',
        MessageType::AREQ => [
            'description' => 'The authentication flow starts.',
        ],
        MessageType::ARES => [
            'description' => 'Response to Authentication Request (AReq)',
        ],
        MessageType::RREQ => [
            'description' => 'Authentication results are reported.',
        ],
        MessageType::RRES => [
            'description' => '3DS server sends a message indicating that the response request (RReq) was received.',
        ],
        MessageType::CREQ => [
            'description' => 'Initiates the cardholder interaction in a challenge flow.',
        ],
        MessageType::CRES => [
            'description' => 'Response to the challenge request (CReq).',
        ],
        'export' => [
            'note' => 'This document has been generated automatically by <strong>:name</strong>, if you require additional information please contact us through the following contacts:',
            'email' => '<strong>E-mail: </strong>:email',
            'phone' => '<strong>Phones: </strong>:phone',
            'hidden_field' => 'Hidden content',
        ],
    ],
    'traces' => [
        'titles' => [
            'authorization' => 'OAuth Authorization service',
            'cardholder' => 'Cardholder service traces',
            'sms_diners' => 'SMS Diners service traces',
            'sms_core' => 'SMS Core API service traces',
            'questionnaire' => 'Questionnaire service traces',
            'out_of_band' => 'Out of Band service traces',
        ],
        'authorization' => [
            'request' => 'A request was made to the service',
            'response' => 'Response to the service request',
            'error' => 'OAuth Authorization service error',
        ],
        'cardholder' => [
            'request' => 'A request was made to the service',
            'response' => 'Response to the service request',
            'error' => 'Cardholder service error',
        ],
        'brands' => [
            'types' => [
                'daf' => 'Visa Digital Authentication Framework (DAF)',
                'mastercard_ds_logic' => 'Mastercard 3RI transactions',
            ],
            'daf' => [
                'actions' => [
                    'label' => [
                        DAFActions::APPROVE => 'Approve',
                        DAFActions::AUTHENTICATE => 'Authenticate by challenge',
                        DAFActions::DECIDE => 'Issuer makes decision',
                        DAFActions::DENY => 'Deny',
                        DAFActions::ISSUER_DENY => 'Issuer decision.',
                    ],
                    'description' => [
                        DAFActions::APPROVE => 'The cardholder is acting as a low risk authenticated payment '
                            . 'credential, the authentication will be approved.',
                        DAFActions::AUTHENTICATE => 'The cardholder acts as an unauthenticated payment credential, '
                            . 'a verification challenge will be performed, if the challenge is completed '
                            . 'successfully, the cardholder will be enrolled in DAF',
                        DAFActions::DECIDE => 'The cardholder acts as an authenticated payment credential but '
                            . 'the transaction is medium-high risk, fraud control lists and rules will be '
                            . 'enforced, challenges will not be allowed.',
                        DAFActions::DENY => 'The cardholder\'s current status is blocked, invalid, or unknown, '
                            . 'therefore authentication is denied.',
                        DAFActions::ISSUER_DENY => 'Due to the challenges are forbidden for authenticated payment '
                            . 'credentials in DAF, this transaction does not was authenticated.',
                    ],
                ],
            ],
            'mastercard_ds_logic' => [
                'label' => 'Decoupled challenge',
                'description' => '3RI transactions with flags 03 (Add Card), 04 (Maintain Card Information), or '
                    . '05 (Verify Account) must be authenticated through a decoupled challenge.',
            ],
        ],
    ],
    'services' => [
        'otp_strategy' => [
            'diners' => [
                'validate' => [
                    'request' => 'The OTP was sent to be validated by Diners service',
                    'response' => 'The OTP was successfully validated by Diners service',
                    'error' => 'An error occurred during OTP validation',
                    'codes' => [
                        '0' => 'OTP successfully validated',
                        '1' => 'The OTP could not be validate (mock)',
                        '56' => 'The OTP entered does not match the one provided to you',
                        '57' => 'The OTP is blocked',
                        '58' => 'The OTP does not contain the validation code',
                        '61' => 'The OTP has expired, a new one is generated automatically',
                        '67' => 'The OTP has been rooted to the provider',
                        '0099' => 'OTP validation system error',
                        '903' => 'An OTP was not generated for the transaction due to a technical error',
                        '99' => 'An error occurred while validating the OTP for the transaction',
                        '98' => 'An error occurred while validating the OTP for the transaction',
                    ],
                ],
                'send' => [
                    'request' => 'The OTP was requested to the Diners service',
                    'response' => 'The OTP was received from the Diners service',
                    'error' => 'An error occurred while sending OTP',
                    'codes' => [
                        '0' => 'Successful response',
                        '903' => 'An OTP was not generated for the transaction due to a technical error',
                        '99' => 'An OTP was not generated for the transaction due to a technical error',
                        '9999' => 'An OTP was not generated for the transaction due to an error with the card',
                    ],
                ],
            ],
            'core' => [
                'request' => 'The OTP was requested to be sent by SMS Core API service.',
                'response' => 'The OTP was successfully sent by SMS Core API service.',
                'error' => 'An error occurred while sending OTP',
            ],
        ],
        'cardholder_strategy' => [
            'standard' => [
                'description' => 'The request for cardholder information has been made from the standard service with authentication',
            ],
            'standard_no_auth' => [
                'description' => 'The cardholder information request has been made from the standard service without authentication',
            ],
        ],
        'questionnaire' => [
            QuestionnaireServiceTracer::GET_QUESTIONNAIRE => [
                'request' => 'A request was sent to get the questionnaire.',
                'response' => 'A questionnaire was received from the service.',
                'error' => 'An error occurred while obtaining the questionnaire.',
            ],
            QuestionnaireServiceTracer::VERIFY_ANSWERS => [
                'request' => 'A request was sent to verify the questionnaire answers.',
                'response' => [
                    'passed' => 'The questionnaire answers passed verification.',
                    'didnt_pass' => 'The questionnaire answers did not pass verification.',
                ],
                'error' => 'An error occurred while verifying the questionnaire answers.',
            ],
            QuestionnaireServiceTracer::GET_ANSWERS => [
                'request' => 'A request was sent to get the questionnaire answers.',
                'response' => 'The questionnaire answers were received from the service.',
                'error' => 'An error occurred while obtaining the questionnaire answers.',
            ],
        ],
        'out_of_band' => [
            OutOfBandServiceTracer::CREATE_SESSION => [
                'request' => 'A request was sent to create a session.',
                'response' => 'The session was created successfully.',
                'error' => 'An error occurred while creating the session.',
            ],
            OutOfBandServiceTracer::VERIFY_SESSION => [
                'request' => 'A request was sent to verify the session.',
                'response' => [
                    'passed' => 'The session passed verification.',
                    'didnt_pass' => 'The session did not pass verification.',
                ],
                'error' => 'An error occurred while verifying the session.',
            ],
        ],
        'status' => [
            'failed' => 'Falló',
            'successful' => 'Exitoso',
            'not_recognised' => 'No reconocido',
            'rules_not_found' => 'Reglas no encontradas',
            'unauthenticated' => 'No autenticado',
            'wrong_format_headers' => 'Cabeceras con formato incorrecto',
            'wrong_authentication_headers' => 'Cabeceras de autenticación incorrectas',
            'required_data_element_missing' => 'Faltan datos requeridos',
            'format_of_elements_is_invalid' => 'Formato de datos inválido',
        ],
    ],
    'flows' => [
        'friction' => 'With friction',
        'frictionless' => 'Frictionless',
        'label' => 'Flow',
    ],
    'eci' => [
        'label' => 'eci',
    ],
    'trans_status_reason' => [
        'label' => 'Trans status reason',
    ],
    'trans_type' => [
        'label' => 'Trans type',
    ],
    'authentication_type' => [
        'label' => 'Authentication type',
    ],
    'authentication_method' => [
        'label' => 'Authentication method',
    ],
    'frequency' => 'Authentication by :frequency|Authentications by :frequency',
    'message' => [
        'merchant_name' => 'Merchant Name:',
        'mcc' => 'Merchant Category Code:',
        'merchant_id' => 'Merchant ID:',
    ],
    'challenge_statuses' => [
        'not_accepted' => 'The cardholder did not accept the challenge',
        'canceled' => 'The cardholder canceled the challenge',
        'failed' => 'The cardholder failed the challenge',
        'abandoned' => 'The cardholder abandoned the challenge',
        'passed' => 'The cardholder passed the challenge',
        'in_progress' => 'The challenge is in progress',
    ],
    'fields' => [
        'acs_trans_id' => 'ACS Transaction ID',
        'date' => 'Created at',
    ],
    'identifiers_fields' => [
        'acs_trans_id' => 'ACS Transaction ID',
        'ds_trans_id' => 'DS Transaction ID',
        'threeds_server_trans_id' => '3DS Server Transaction ID',
        'sdk_trans_id' => 'SDK Transaction ID',
        'authentication_value' => 'Authentication value',
    ],
    'methods' => [
        'text' => 'One-time passcode',
        'oob' => 'Out of band',
        'single_select' => 'Single select questionnaire',
        'multi_select' => 'Multiple select questionnaire',
    ],
    'cavv' => [
        'default' => 'Brand default algorithm',
        'mastercard' => [
            'default' => 'Mastercard using full card PAN and Directory Server transaction ID',
            'ds' => 'Mastercard using Directory Server transaction ID',
        ],
    ],
    'key_indicators' => [
        'one' => 'Indicator No. 01',
        'two' => 'Indicator No. 02',
        'three' => 'Indicator No. 03',
        'four' => 'Indicator No. 04',
        'five' => 'Indicator No. 05',
        'six' => 'Indicator No. 06',
        'seven' => 'Indicator No. 07',
        'eight' => 'Indicator No. 08',
    ],
];
